### ISSUE TITLE
長文を書くと、previewも長くなり本文入力Windowまでの距離が遠くなり、記述が困難になる

### ISSUE THREAD

**Issue by hymkor** [hymkor/wifky#3]
いただいたリクエストは以下のとおり：

https://x.com/canaan18/status/1909173157350744532

> WifkyのnikkyPlug-inへの要望です。
画像を多用した長文の日記を書いた場合、previewも長くなり本文入力Windowまでの距離が遠くなり、previewを確認しながら日記記述が困難になります。preview表示にスクロールバーをつける、入力ウインドウをpreviewより上にする等の対応を検討頂けないでしょうか。

**Comment by hymkor** [comment]
#### 表示例３：縦分割

![Image](https://github.com/user-attachments/assets/406afa1f-65cc-4099-823b-9d4e0d4b680e)

追加する CSS

```css
html, body {
  height: 100%;
  margin: 0;
}

div.preview_table {
  display: flex;
  flex-direction: column;
  height: 100vh;
}

div.preview_edit_column, div.preview_view_column {
  height: 50%;
  overflow: auto;
  box-sizing: border-box;
  padding: 10px;
}
```
